### ISSUE TITLE
build fails locally on `master`

### ISSUE THREAD

**Issue by michalmikolajczyk** [michalmikolajczyk/viking-garage-frontend#63]
new pull, `npm i`, `npm start`:
```
Michals-MacBook-Pro:viking-garage-frontend michalmikolajczyk$ npm start

> viking-garage-frontend@0.5.5 start /Users/michalmikolajczyk/dev/viking-garage-frontend
> env NODE_ENV=production node ./server

Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
/Users/michalmikolajczyk/dev/viking-garage-frontend/dist/ssr.js:72
!function(n,r){var o=function(e){return new l(e)};o.version="0.2";var a=n.fxSetup||{rates:{},base:""};o.rates=a.rates,o.base=a.base,o.settings={from:a.from||o.base,to:a.to||o.base};var i=o.convert=function(e,t){if("object"==typeof e&&e.length){for(var n=0;n<e.length;n++)e[n]=i(e[n],t);return e}return t=t||{},t.from||(t.from=o.settings.from),t.to||(t.to=o.settings.to),e*s(t.to,t.from)},s=function(e,t){var n=o.rates;if(n[o.base]=1,!n[e]||!n[t])throw"fx error";return t===o.base?n[e]:e===o.base?1/n[t]:n[e]*(1/n[t])},l=function(e){"string"==typeof e?(this._v=parseFloat(e.replace(/[^0-9-.]/g,"")),this._fx=e.replace(/([^A-Za-z])/g,"")):this._v=e},u=o.prototype=l.prototype;u.convert=function(){var e=Array.prototype.slice.call(arguments);return e.unshift(this._v),i.apply(o,e)},u.from=function(e){var t=o(i(this._v,{from:e,to:o.base}));return t._fx=o.base,t},u.to=function(e){return i(this._v,{from:this._fx?this._fx:o.settings.from,to:e})},"undefined"!=

ReferenceError: window is not defined
    at Function.o [as useColors] (/Users/michalmikolajczyk/dev/viking-garage-frontend/dist/ssr.js:72:7740)
    at Function.o (/Users/michalmikolajczyk/dev/viking-garage-frontend/dist/ssr.js:72:10000)
    at Object.<anonymous> (/Users/michalmikolajczyk/dev/viking-garage-frontend/dist/ssr.js:72:4958)
    at t (/Users/michalmikolajczyk/dev/viking-garage-frontend/dist/ssr.js:1:183)
    at Object.<anonymous> (/Users/michalmikolajczyk/dev/viking-garage-frontend/dist/ssr.js:72:1418)
    at t (/Users/michalmikolajczyk/dev/viking-garage-frontend/dist/ssr.js:1:183)
    at Object.module.exports.Object.defineProperty.value (/Users/michalmikolajczyk/dev/viking-garage-frontend/dist/ssr.js:52:27777)
    at t (/Users/michalmikolajczyk/dev/viking-garage-frontend/dist/ssr.js:1:183)
    at Object.<anonymous> (/Users/michalmikolajczyk/dev/viking-garage-frontend/dist/ssr.js:27:13724)
    at t (/Users/michalmikolajczyk/dev/viking-garage-frontend/dist/ssr.js:1:183)

npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/michalmikolajczyk/.nvm/versions/node/v7.10.0/bin/node" "/Users/michalmikolajczyk/.nvm/versions/node/v7.10.0/bin/npm" "start"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! viking-garage-frontend@0.5.5 start: `env NODE_ENV=production node ./server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the viking-garage-frontend@0.5.5 start script 'env NODE_ENV=production node ./server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the viking-garage-frontend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     env NODE_ENV=production node ./server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs viking-garage-frontend
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls viking-garage-frontend
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/michalmikolajczyk/.npm/_logs/2017-06-19T23_28_22_685Z-debug.log
```

**Comment by jonzee** [comment]
done in #75
